version: '3'
services:
  backend:
    build:
      context: backend
  db-backend:
    build:
      context: db-backend
    container_name: db-backend
    ports:
      - "27017-27019:27017-27019"
  db-nlp:
    build:
      context: db-nlp
  frontend:
    build:
      context: frontend
    ports:
      - "80:80"
      - "443:443"
